# run_example.R
# ---------------
# Example of the full pipeline, run against the simulated data.
# Run this from the ssnpt_pipeline/ folder.

# 1. Install package dependencies (one-time)
# install.packages(c("dplyr", "rmarkdown", "officer", "flextable", "devtools"))

# 2. Load the package functions (using devtools::load_all for local dev,
#    since the package isn't published to CRAN)
devtools::load_all("ssnptReport")

# 3. Read the simulated data (generated by python_plug/simulate_data.py)
df <- read.csv("python_plug/simulated_data.csv", stringsAsFactors = FALSE)

# 4. Compute the 8 subscale scores
df_scored <- compute_subscale_scores(df)

# 5. Generate a Word report for every district at once
#    (min_n = 5 is a placeholder -- confirm the real threshold with your
#    professor/IRB before using this on real data)
generate_all_district_reports(df_scored, min_n = 5, output_dir = "district_reports")

# Reports will be written to district_reports/SSNPT-R_Report_D001.docx, etc.
# Districts with fewer than min_n respondents will get a report that says
# results are suppressed, rather than showing (possibly identifiable) averages.
